[package]
name = "passwords"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/passwords"
homepage = "https://magiclen.org/passwords"
keywords = ["password", "score", "strength", "secure", "generate"]
categories = ["algorithms"]
description= "This crate provides useful tools to generate multiple readable passwords, as well as analyze and score them."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/passwords", branch = "master" }
appveyor = { repository = "magiclen/passwords", branch = "master", service = "github" }

[dependencies]
random-pick = "1.2"

[dev-dependencies]
regex = "1"